### ISSUE TITLE
1.3.1-13 fails to load KSC scene, Duna SSTV audio plays

### ISSUE THREAD

**Issue by gordonfpanam** [Kopernicus/Kopernicus-Backport#1]
Vanilla Kopernicus installation with no additional changes fails to load KSC scene on startup.  Logs, screen shot of GameData folder, and link to example video all attached.

1.3.1-12 does load and play, though ground colour is all wrong; that's a different problem.

[KSP131-Kopernicus131-13.zip](https://github.com/Kopernicus/Kopernicus-Backport/files/2354960/KSP131-Kopernicus131-13.zip)

![kopernicus131-13](https://user-images.githubusercontent.com/25485283/45127629-dbe35e80-b13e-11e8-8be9-18a25ace12df.png)

https://youtu.be/-AEmORvbH4g

**Comment by Tonas1997** [comment]
Also having this issue.

**Comment by StollD** [comment]
Fixed with https://github.com/Kopernicus/Kopernicus/commit/82abd9350018cfaf8d485a81b422e75f56192630, the next backport release should work as expected.

Next time there is an issue, please post it on the Kopernicus repository, since I don't see them here (found this by accident). I think I am going to disable the issue tracker here.
